import = ["/home/weldyss/.config/alacritty/themes/tokyo-night.toml"]

[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
blinking = "Off"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "FantasqueSansM Nerd Font"

[font.bold]
family = "FantasqueSansM Nerd Font"

[font.italic]
family = "FantasqueSansM Nerd Font"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
dynamic_padding = true
dynamic_title = true

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 3
y = 3
