[general]
import = [ "~/.config/alacritty/themes/tokyo-night.toml" ]

[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
blinking = "Off"
shape = "Beam"

[env]
# TERM = "xterm-256color"
# program = "zellij"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{},<>"
save_to_clipboard = true

[window]
dynamic_title = true
dynamic_padding = true
startup_mode = "Windowed"
decorations_theme_variant = "None"
opacity = 0.9
blur = true
padding.x = 0
padding.y = 0
decorations = "None"

[window.dimensions]
columns = 120
lines = 40

[font]
size = 15
normal = { family = "CaskaydiaMono Nerd Font", style = "ExtraLight" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Light" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }

[scrolling]
history = 10_000

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]
