import = [ "~/.config/alacritty/themes/tokyo-night.toml" ]

[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
blinking = "Off"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "FantasqueSansM Nerd Font"

[font.bold]
family = "FantasqueSansM Nerd Font"

[font.italic]
family = "FantasqueSansM Nerd Font"

[shell]
# program = "zellij"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{},<>"
save_to_clipboard = true

[window]
dynamic_title = true
dynamic_padding = true
startup_mode = "Windowed"
decorations_theme_variant = "None"
decorations = "None"
opacity = 0.9
blur = true
padding.x = 30
padding.y = 30
decorations = "None"
opacity = 0.98

  [window.dimensions]
  columns = 120
  lines = 40

[cursor.style]
shape = "Beam"
blinking = "Off"

[font]
size = 15
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }

[scrolling]
history = 10_000

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
dynamic_padding = true
dynamic_title = true

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 3
y = 3

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]
